apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak-pod
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 32080
      name: keycloak-https-port # Map Keycloak's HTTPS port
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32030
      name: nodejs-port
  type: NodePort  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres-port
  type: ClusterIP  