apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres-pod
spec:
  containers:
    - name: postgres
      image: postgres:latest
      env:
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        - name: POSTGRES_DB
          value: "keycloak"
      ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: mailhog-pod
  labels:
    app: mailhog-pod
spec:
  containers:
    - name: mailhog
      image: mailhog/mailhog:latest
      ports:
        - containerPort: 1025 # SMTP Port
        - containerPort: 8025 # Web UI Port
---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak-pod
  labels:
    app: keycloak-pod
spec:
  containers:
    - name: keycloak
      image: custom-keycloak:latest
      imagePullPolicy: IfNotPresent # Use local image if available
      env:
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres-service:5432/keycloak"
        - name: KC_DB_USERNAME
          value: "keycloak"
        - name: KC_DB_PASSWORD
          value: "mypassword"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
        - name: KC_HOSTNAME
          value: "10.151.130.198"
        - name: KC_HTTPS_PORT
          value: "8443" # Explicitly configure HTTPS port
        - name: KC_HTTPS_CERTIFICATE_FILE
          value: "/opt/keycloak/demo/certs/tls.crt"
        - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          value:  "/opt/keycloak/demo/certs/tls.key"
        - name: KC_EMAIL_HOST
          value: "mailhog-service"  # Name of the MailHog service
        - name: KC_EMAIL_PORT
          value: "1025"             # MailHog SMTP port
        - name: KC_EMAIL_FROM
          value: "no-reply@test.keycloak.org"  # Sender email address
        - name: KC_EMAIL_AUTH
          value: "false"            # MailHog does not require authentication
      ports:
        - containerPort: 8443
      volumeMounts:
      - name: certsvol
        mountPath: /opt/keycloak/demo/certs
  volumes:
  - name: certsvol
    secret:
      secretName: my-tls-secret
