apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak-pod
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 32080
      name: keycloak-https-port # Map Keycloak's HTTPS port
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32081
      name: postgres-port
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  selector:
    app: mailhog-pod
  ports:
    - protocol: TCP
      port: 1025 # SMTP Port
      targetPort: 1025
      nodePort: 32025
      name: smtp-port
    - protocol: TCP
      port: 8025 # Web UI Port
      targetPort: 8025
      nodePort: 32026
      name: web-ui-port
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32082
      name: jenkins-ui
    - protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 32083
      name: jenkins-agent
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus-pod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32084
      name: nexus-web
  type: NodePort
