apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak-pod
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 32080
      name: keycloak-https-port # Map Keycloak's HTTPS port
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32081
      name: postgres-port
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  selector:
    app: mailhog-pod
  ports:
    - protocol: TCP
      port: 1025 # SMTP Port
      targetPort: 1025
      nodePort: 32025
      name: smtp-port
    - protocol: TCP
      port: 8025 # Web UI Port
      targetPort: 8025
      nodePort: 32026
      name: web-ui-port
  type: NodePort
